export const services = [
  { name: "Plumbing", profession: "Plumber", description: "Pipe repairs, leakage fixing, tap and sink installation, drainage cleaning." },
  { name: "Electrical Services", profession: "Electrician", description: "Wiring installation, circuit repair, fan and light fixture installation, power backup solutions." },
  { name: "Carpentry", profession: "Carpenter", description: "Custom woodwork, furniture repair, door/window fixing, wooden flooring installation." },
  { name: "Painting", profession: "Painter", description: "House painting, wall painting, furniture polishing, waterproof coating." },
  { name: "Air Conditioning Services", profession: "AC Technician", description: "AC installation, servicing, gas refilling, cooling issue repair." },
  { name: "Refrigerator Repair", profession: "Refrigeration Technician", description: "Cooling issues, compressor repair, gas refilling, defrost problems." },
  { name: "Washing Machine Repair", profession: "Appliance Repair Technician", description: "Washing machine installation, drum repair, drainage issues, motor service." },
  { name: "Television Repair", profession: "TV Technician", description: "LED/LCD screen repair, sound issues, wall mounting, display replacement." },
  { name: "Geyser & Water Heater Repair", profession: "Geyser Technician", description: "Water heating issues, thermostat replacement, leakage fixing." },
  { name: "Microwave & Oven Repair", profession: "Microwave Technician", description: "Heating issues, keypad replacement, turntable problems, door fixing." },
  { name: "Pest Control Services", profession: "Pest Control Specialist", description: "Termite treatment, mosquito and cockroach control, rodent extermination." },
  { name: "House Cleaning Services", profession: "Cleaning Specialist", description: "Deep cleaning, floor scrubbing, bathroom cleaning, kitchen degreasing." },
  { name: "Sofa & Carpet Cleaning", profession: "Upholstery Cleaner", description: "Carpet shampooing, vacuum deep cleaning, stain removal, odor treatment." },
  { name: "Chimney & Kitchen Exhaust Cleaning", profession: "Chimney Technician", description: "Oil filter cleaning, motor service, smoke vent cleaning." },
  { name: "Water Purifier Service", profession: "RO Technician", description: "RO filter change, UV purification maintenance, water quality testing." },
  { name: "Gardening & Landscaping", profession: "Gardener", description: "Lawn mowing, plant care, landscaping, tree trimming." },
  { name: "Home Security & CCTV Installation", profession: "Security System Installer", description: "CCTV installation, camera troubleshooting, alarm system setup." },
  { name: "Locksmith Services", profession: "Locksmith", description: "Key duplication, lock repair, new lock installation, emergency unlocking." },
  { name: "Glass & Mirror Repair", profession: "Glass Technician", description: "Window glass replacement, mirror installation, custom glasswork." },
  { name: "Masonry & Tiling", profession: "Mason", description: "Floor tiling, wall plastering, marble polishing, brickwork repair." },
];

export const serviceCategories = [
  "Plumber",
  "Electrician",
  "Carpenter",
  "Painter",
  "AC Technician",
  "Refrigeration Technician",
  "Appliance Repair Technician",
  "TV Technician",
  "Geyser Technician",
  "Microwave Technician",
  "Pest Control Specialist",
  "Cleaning Specialist",
  "Upholstery Cleaner",
  "Chimney Technician",
  "RO Technician",
  "Gardener",
  "Security System Installer",
  "Locksmith",
  "Glass Technician",
  "Mason"
]